version: '2'
services:
    gdprlozano-app:
        image: gdprlozano
        environment:
            - _JAVA_OPTIONS=-Xmx512m -Xms256m
            - SPRING_PROFILES_ACTIVE=prod,swagger
            - SPRING_DATASOURCE_URL=jdbc:mariadb://gdprlozano-mariadb:3306/gdprlozano
            - JHIPSTER_SLEEP=10 # gives time for the database to boot before the application
        ports:
            - 8080:8080
    gdprlozano-mariadb:
        extends:
            file: mariadb.yml
            service: gdprlozano-mariadb
