package es.aldaba.gdpr.domain.enumeration;

/**
 * The NombreOperacion enumeration.
 */
public enum NombreOperacion {
    ACEPTACION_VERSION_LEY, ALTA_SUBSCRIPCION, ANONIMIZACION_CONTACTO, BAJA_SUBSCRIPCION, CONFIRMADA_BAJA_LEY, CONSULTA_ESTADO_LEY, CREACION_CONTACTO, DECLINACION_CONTACTO, DECLINACION_VERSION_LEY, ENVIO_LEY, RECHAZO_ACEPTA_LEY_POR_VENCIMIENTO, SOLICITUD_BAJA_LEY
}
